blocos={
'0000':'Abertura do Arquivo Digital e Identificação da entidade',
'0001':'Abertura do Bloco 0',
'0002':'Classificação do Estabelecimento Industrial ou Equiparado a Industrial',
'0005':'Dados Complementares da entidade',
'0015':'Dados do Contribuinte Substituto ou Responsável pelo ICMS Destino',
'0100':'Dados do Contabilista',
'0150':'Tabela de Cadastro do Participante',
'0175':'Alteração da Tabela de Cadastro de Participante',
'0190':'Identificação das unidades de medida',
'0200':'Tabela de Identificação do Item (Produtos e Serviços)',
'0205':'Alteração do Item',
'0206':'Código de produto conforme Tabela ANP',
'0210':'Consumo Específico Padronizado',
'0220':'Fatores de Conversão de Unidades',
'0300':'Cadastro de bens ou componentes do Ativo Imobilizado',
'0305':'Informação sobre a Utilização do Bem',
'0400':'Tabela de Natureza da Operação/ Prestação',
'0450':'Tabela de Informação Complementar do documento fiscal',
'0460':'Tabela de Observações do Lançamento Fiscal',
'0500':'Plano de contas contábeis',
'0600':'Centro de custos',
'0990':'Encerramento do Bloco 0',
'B001':'Abertura do Bloco B',
'B020':'Nota Fiscal (código 01), Nota Fiscal de Serviços (código 03), Nota Fiscal de Serviços Avulsa (código 3B), Nota Fiscal de Produtor (código 04), Conhecimento de Transporte Rodoviário de Cargas (código 08), NF-e (código 55) e NFC-e (código 65)',
'B025':'Detalhamento por combinação de alíquota e item da lista de serviços da Lei Complementar nº 116/2003',
'B030':'Nota Fiscal de Serviços Simplificada (código 3A)',
'B035':'Detalhamento por combinação de alíquota e item da lista de serviços da Lei Complementar nº 116/2003',
'B350':'Serviços prestados por instituições financeiras',
'B420':'Totalização dos valores de serviços prestados por combinação de alíquota e item da lista de serviços da Lei Complementar nº 116/2003',
'B440':'Totalização dos valores retidos',
'B460':'Deduções do ISS',
'B470':'Apuração do ISS',
'B500':'Apuração do ISS sociedade uniprofissional',
'B510':'Uniprofissional – empregados e sócios',
'B990':'Encerramento do Bloco B',
'C001':'Abertura do Bloco C',
'C100':'Documento - Nota Fiscal (código 01), Nota Fiscal Avulsa (código 1B), Nota Fiscal de Produtor (código 04), Nota Fiscal Eletrônica (código 55) e Nota Fiscal Eletrônica para Consumidor Final (código 65)',
'C101':'Informação complementar dos documentos fiscais quando das operações inte-restaduais destinadas a consumidor final não contribuinte EC 87/15 (código 55)',
'C105':'Operações com ICMS ST recolhido para UF diversa do destinatário do docu- mento fiscal (Código 55)',
'C110':'Complemento de Documento - Informação Complementar da Nota Fiscal(código 01, 1B, 55)',
'C111':'Complemento de Documento - Processo referenciado',
'C112':'Complemento de Documento - Documento de Arrecadação Referenciado',
'C113':'Complemento de Documento - Documento Fiscal Referenciado',
'C114':'Complemento de Documento - Cupom Fiscal Referenciado',
'C115':'Local de coleta e/ou entrega (CÓDIGOS 01, 1B e 04)',
'C116':'Cupom Fiscal Eletrônico - CF-e referenciado',
'C120':'Complemento de Documento - Operações de Importação (código 01 e 55)',
'C130':'Complemento de Documento - ISSQN, IRRF e Previdência Social',
'C140':'Complemento de Documento - Fatura (código 01)',
'C141':'Complemento de Documento - Vencimento da Fatura (código 01)',
'C160':'Complemento de Documento - Volumes Transportados (código 01 e 04) Exceto Combustíveis',
'C165':'Complemento de Documento - Operações com combustíveis (código 01)',
'C170':'Complemento de Documento - Itens do Documento (código 01, 1B, 04 e 55)',
'C171':'Complemento de Item - Armazenamento de Combustíveis (código 01,55)',
'C172':'Complemento de Item - Operações com ISSQN (código 01)',
'C173':'Complemento de Item - Operações com Medicamentos (código 01,55)',
'C174':'Complemento de Item - Operações com Armas de Fogo (código 01)',
'C175':'Complemento de Item - Operações com Veículos Novos (código 01,55)',
'C176':'Complemento de Item -Ressarcimento de ICMS em operações com Substituição Tributária (código 01,55)',
'C177':'Complemento de Item – Outras informações (Cód. 01, 55) – (Válido a partir de 01/01/2019)',
'C178':'Complemento de Item - Operações com Produtos Sujeitos a Tributação de IPI por Unidade ou Quantidade de produto',
'C179':'Complemento de Item - Informações Complementares ST (código 01)',
'C180':'Informações complementares das operações de entrada de mercadorias sujeitas à substituição tributária (código 01, 1B, 04 e 55)',
'C181':'Informações complementares das operações de devolução de saídas de mercadorias sujeitas à substituição tributária (código 01, 1B, 04 e 55).',
'C185':'Informações complementares das operações de saída de mercadorias sujeitas à substituição tributária (código 01, 1B, 04 e 55)',
'C186':'Informações complementares das operações de devolução de entradas de mer cadorias sujeitas à substituição tributária (código 01, 1B, 04 e 55).',
'C190':'Registro Analítico do Documento (código 01, 1B, 04, 55 e 65)',
'C191':'Informações do Fundo de Combate à Pobreza – FCP – na NF-e (Código 55)',
'C195':'Complemento do Registro Analítico - Observações do Lançamento Fiscal (código 01, 1B, 04 e 55) ',
'C197':'Outras Obrigações Tributárias, Ajustes e Informações provenientes de Documento Fiscal',
'C300':'Documento - Resumo Diário das Notas Fiscais de Venda a Consumidor (código 02)',
'C310':'Documentos Cancelados de Nota Fiscal de Venda a Consumidor (código 02)',
'C320':'Registro Analítico das Notas Fiscais de Venda a Consumidor (código 02)',
'C321':'Itens dos Resumos Diários dos Documentos (código 02)',
'C330':'Informações complementares das operações de saída de mercadorias sujeitas à substituição tributária (código 02)',
'C350':'Nota Fiscal de venda a consumidor (código 02)',
'C370':'Itens do documento (código 02)',
'C380':'Informações complementares das operações de saída de mercadorias sujeitas à substituição tributária (código 02)',
'C390':'Registro Analítico das Notas Fiscais de Venda a Consumidor (código 02)',
'C400':'Equipamento ECF (código 02, 2D e 60)',
'C405':'Redução Z (código 02, 2D e 60)',
'C410':'PIS e COFINS Totalizados no Dia (código 02 e 2D)',
'C420':'Registro dos Totalizadores Parciais da Redução Z (código 02, 2D e 60)',
'C425':'Resumo de itens do movimento diário (código 02 e 2D)',
'C430':'Informações complementares das operações de saída de mercadorias sujeitas à substituição tributária (código 02, 2D e 60)',
'C460':'Documento Fiscal Emitido por ECF (código 02, 2D e 60)',
'C465':'Complemento do Cupom Fiscal Eletrônico Emitido por ECF - CF-e-ECF (código 60)',
'C470':'Itens do Documento Fiscal Emitido por ECF (código 02 e 2D)',
'C480':'Informações complementares das operações de saída de mercadorias sujeitas à substituição tributária (código 02, 2D e 60)',
'C490':'Registro Analítico do movimento diário (código 02, 2D e 60)',
'C495':'Resumo Mensal de Itens do ECF por Estabelecimento (código 02 e 2D e 2E)',
'C500':'Nota Fiscal/Conta de Energia Elétrica (código 06), Nota Fiscal de Energia Elétrica Eletrônica (código 66) , Nota Fiscal/Conta de fornecimento dágua canalizada (código 29) e Nota Fiscal/Consumo Fornecimento de Gás (Código 28)',
'C510':'Itens do Documento - Nota Fiscal/Conta de Energia Elétrica (código 06), Nota Fiscal/Conta de fornecimento d\'água canalizada (código 29) e Nota Fiscal/Conta Fornecimento de Gás (Código 28)',
'C590':'Registro Analítico do Documento - Nota Fiscal/Conta de Energia Elétrica (código 06), Nota Fiscal de Energia Elétrica Eletrônica (código 66), Nota Fis- cal/Conta de fornecimento d\'água canalizada (código 29) e Nota Fiscal/Conta Fornecimento de Gás (Código 28)',
'C591':'Informações do Fundo de Combate à Pobreza – FCP na NF3e (código 66)',
'C595':'Observações do Lançamento Fiscal (códigos 06, 28, 29 e 66)',
'C597':'Outras obrigações tributárias, ajustes e informações de valores provenientes de documento fiscal.',
'C600':'Consolidação Diária de Notas Fiscais/Contas de Energia Elétrica (Código 06), Nota Fiscal/Conta de Fornecimento d´água (código 29) e Nota Fiscal/Conta de Fornecimento de Gás (Código 28) - (Empresas não obrigadas ao Convênio ICMS 115/03)',
'C601':'Documentos cancelados - Consolidação diária de notas fiscais/conta de energia elétrica (Código 06), nota fiscal/conta de fornecimento de água (código 29) e nota fiscal/conta de fornecimento de gás (código 28)',
'C610':'Itens do Documento Consolidado - Notas Fiscais/Contas de Energia Elétrica (Código 06), Nota Fiscal/Conta de Fornecimento d´água (código 29) e Nota Fiscal/Conta de Fornecimento de Gás (Código 28) - (Empresas não obrigadas ao Convênio ICMS 115/03)',
'C690':'Registro Analítico dos Documentos - Notas Fiscais/Contas de Energia Elétrica (Código 06), Nota Fiscal/Conta de Fornecimento d´água (código 29) e Nota Fiscal/Conta de Fornecimento de Gás (Código 28)',
'C700':'Consolidação dos Documentos Nota Fiscal/Conta Energia Elétrica (código 06) emitidas em via única - (Empresas obrigadas à entrega do arquivo previsto no Convênio ICMS 115/03) e Nota Fiscal/Conta de Fornecimento de Gás Canalizado (Código 28)',
'C790':'Registro Analítico dos Documentos - Nota Fiscal/Conta Energia Elétrica (códi- go 06) emitidas em via única',
'C791':'Registro de Informações de ICMS ST por UF',
'C800':'Registro Cupom Fiscal Eletrônico - CF-e (Código 59)',
'C810':'Itens do documento do cupom fiscal eletrônico – SAT (CF-E-SAT) (código 59)',
'C815':'Informações complementares das operações de saída de mercadorias sujeitas à substituição tributária (CF-E-SAT) (código 59)',
'C850':'Registro Analítico do CF-e (Código 59)',
'C860':'Identificação do equipamento SAT-CF-e (Código 59)',
'C870':'Itens do documento do cupom fiscal eletrônico – SAT (CF-E-SAT) (código 59)',
'C880':'Informações complementares das operações de saída de mercadorias sujeitas à substituição tributária (CF-E-SAT) (código 59)',
'C890':'Resumo diário de CF-e (Código 59) por equipamento SAT-CF-e',
'C990':'Encerramento do Bloco C',
'D001':'Abertura do Bloco D',
'D100':'Nota Fiscal de Serviço de Transporte (código 07), Conhecimentos de Transpor- te Rodoviário De Cargas (código 08), Conhecimentos de Transporte de Cargas Avulso (código 8b), Aquaviário de Cargas (código 09), Aéreo (código 10), Fer- roviário de Cargas (código 11), Multimodal de Cargas (código 26), Nota Fiscal de Transporte Ferroviário de Carga (código 27), Conhecimento de Transporte Eletrônico – CT-e (código 57), Conhecimento de Transporte Eletrônico para Outros Serviços - CT-e OS (código 67) e Bilhete de Passagem Eletrônico (códi- go 63)',
'D101':'Informação complementar dos documentos fiscais quando das prestações inte- restaduais destinadas a consumidor final não contribuinte EC 87/15 (código 57 e 67)',
'D110':'Itens do documento - Nota Fiscal de Serviços de Transporte (código 07)',
'D120':'Complemento da Nota Fiscal de Serviços de Transporte (código 07)',
'D130':'Complemento do Conhecimento Rodoviário de Cargas (código 08) e Conheci- mento de Transporte de Cargas Avulso (Código 8B)',
'D140':'Complemento do Conhecimento Aquaviário de Cargas (código 09)',
'D150':'Complemento do Conhecimento Aéreo de Cargas (código 10)',
'D160':'Carga Transportada (CÓDIGO 08, 8B, 09, 10, 11, 26 E 27)',
'D161':'Local de Coleta e Entrega (códigos 08, 8B, 09, 10, 11 e 26)',
'D162':'Identificação dos documentos fiscais (código 08,8B, 09,10,11,26 e 27)',
'D170':'Complemento do Conhecimento Multimodal de Cargas (código 26)',
'D180':'Modais (código 26)',
'D190':'Registro Analítico dos Documentos (CÓDIGO 07, 08, 8B, 09, 10, 11, 26, 27,57 e 67) ',
'D195':'Observações do lançamento (CÓDIGO 07, 08, 8B, 09, 10, 11, 26, 27, 57 e 67)',
'D197':'Outras obrigações tributárias, ajustes e informações de valores provenientes do documento fiscal.',
'D300':'Registro Analítico dos bilhetes consolidados de Passagem Rodoviário (código 13), de Passagem Aquaviário (código 14), de Passagem e Nota de Bagagem (código 15) e de Passagem Ferroviário (código 16)',
'D301':'Documentos cancelados dos Bilhetes de Passagem Rodoviário (código 13), de Passagem Aquaviário (código 14), de Passagem e Nota de Bagagem (código 15) e de Passagem Ferroviário (código 16)',
'D310':'Complemento dos Bilhetes (código 13, código 14, código 15 e código 16)',
'D350':'Equipamento ECF (Códigos 2E, 13, 14, 15 e 16)',
'D355':'Redução Z (Códigos 2E, 13, 14, 15 e 16)',
'D360':'PIS E COFINS totalizados no dia (Códigos 2E, 13, 14, 15 e 16)',
'D365':'Registro dos Totalizadores Parciais da Redução Z (Códigos 2E, 13, 14, 15 e 16)',
'D370':'Complemento dos documentos informados (Códigos 13, 14, 15, 16 E 2E)',
'D390':'Registro analítico do movimento diário (Códigos 13, 14, 15, 16 E 2E)',
'D400':'Resumo do Movimento Diário (código 18)',
'D410':'Documentos Informados (Códigos 13, 14, 15 e 16)',
'D411':'Documentos Cancelados dos Documentos Informados (Códigos 13, 14, 15 e 16)',
'D420':'Complemento dos Documentos Informados (Códigos 13, 14, 15 e 16)',
'D500':'Nota Fiscal de Serviço de Comunicação (código 21) e Serviço de Telecomuni- cação (código 22)',
'D510':'Itens do Documento - Nota Fiscal de Serviço de Comunicação (código 21) e Serviço de Telecomunicação (código 22)',
'D530':'Terminal Faturado',
'D590':'Registro Analítico do Documento (códigos 21 e 22)',
'D600':'Consolidação da Prestação de Serviços - Notas de Serviço de Comunicação (código 21) e de Serviço de Telecomunicação (código 22)',
'D610':'Itens do Documento Consolidado (códigos 21 e 22)',
'D690':'Registro Analítico dos Documentos (códigos 21 e 22)',
'D695':'Consolidação da Prestação de Serviços - Notas de Serviço de Comunicação (código 21) e de Serviço de Telecomunicação (código 22)',
'D696':'Registro Analítico dos Documentos (códigos 21 e 22)',
'D697':'Registro de informações de outras UFs, relativamente aos serviços “não-medi- dos” de televisão por assinatura via satélite',
'D990':'Encerramento do Bloco D',
'E001':'Abertura do Bloco E',
'E100':'Período de Apuração do ICMS',
'E110':'Apuração do ICMS - Operações Próprias',
'E111':'Ajuste/Benefício/Incentivo da Apuração do ICMS',
'E112':'Informações Adicionais dos Ajustes da Apuração do ICMS',
'E113':'Informações Adicionais dos Ajustes da Apuração do ICMS - Identificação dos documentos fiscais',
'E115':'Informações Adicionais da Apuração do ICMS - Valores Declaratórios',
'E116':'Obrigações do ICMS Recolhido ou a Recolher - Obrigações Próprias',
'E200':'Período de Apuração do ICMS - Substituição Tributária',
'E210':'Apuração do ICMS - Substituição Tributária',
'E220':'Ajuste/Benefício/Incentivo da Apuração do ICMS - Substituição Tributária',
'E230':'Informações Adicionais dos Ajustes da Apuração do ICMS Substituição Tributá- ria',
'E240':'Informações Adicionais dos Ajustes da Apuração do ICMS Substituição Tributá- ria - Identificação dos documentos fiscais',
'E250':'Obrigações do ICMS a Recolher - Substituição Tributária',
'E300':'Período de Apuração do ICMS Diferencial de Alíquota – UF Origem/Destino EC 87/15',
'E310':'Apuração do ICMS Diferencial de Alíquota – UF Origem/Destino EC 87/15',
'E311':'Ajuste/Benefício/Incentivo da Apuração do ICMS Diferencial de Alíquota – UF Origem/Destino EC 87/15',
'E312':'Informações Adicionais dos Ajustes da Apuração do ICMS Diferencial de Alíquota – UF Origem/Destino EC 87/15',
'E313':'Informações Adicionais da Apuração do ICMS Diferencial de Alíquota – UF Origem/Destino EC 87/15 Identificação dos Documentos Fiscais',
'E316':'Obrigações do ICMS recolhido ou a recolher – Diferencial de Alíquota – UF Origem/Destino EC 87/15',
'E500':'Período de Apuração do IPI',
'E510':'Consolidação dos Valores de IPI',
'E520':'Apuração do IPI',
'E530':'Ajustes da Apuração do IPI',
'E531':'Informações Adicionais dos Ajustes da Apuração do IPI – Identificação dos Documentos Fiscais (01 e 55)',
'E990':'Encerramento do Bloco E',
'G001':'Abertura do Bloco G',
'G110':'ICMS – Ativo Permanente – CIAP',
'G125':'Movimentação de Bem do Ativo Imobilizado',
'G126':'Outros créditos CIAP',
'G130':'Identificação do documento fiscal',
'G140':'Identificação do item do documento fiscal',
'G990':'Encerramento do Bloco G',
'H001':'Abertura do Bloco H',
'H005':'Totais do Inventário',
'H010':'Inventário',
'H020':'Informação complementar do Inventário',
'H030':'Informações complementares do inventário das mercadorias sujeitas ao regime de substituição tributária',
'H990':'Encerramento do Bloco H',
'K001':'Abertura do Bloco K',
'K100':'Período de Apuração do ICMS/IPI',
'K200':'Estoque Escriturado',
'K210':'Desmontagem de mercadorias – Item de Origem',
'K215':'Desmontagem de mercadorias – Item de Destino',
'K220':'Outras Movimentações Internas entre Mercadorias',
'K230':'Itens Produzidos',
'K235':'Insumos Consumidos',
'K250':'Industrialização Efetuada por Terceiros – Itens Produzidos',
'K255':'Industrialização em Terceiros – Insumos Consumidos',
'K260':'Reprocessamento/Reparo de Produto/Insumo',
'K265':'Reprocessamento/Reparo – Mercadorias Consumidas e/ou Retornadas',
'K270':'Correção de Apontamento dos Registros K210, K220, K230, K250 e K260',
'K275':'Correção de Apontamento e Retorno de Insumos dos Registros K215, K220, K235, K255 e K265',
'K280':'Correção de Apontamento – Estoque Escriturado',
'K290':'Produção Conjunta – Ordem de Produção',
'K291':'Produção Conjunta – Itens Produzidos',
'K292':'Produção Conjunta – Insumos Consumidos',
'K300':'Produção Conjunta – Industrialização Efetuada por Terceiros',
'K301':'Produção Conjunta – Industrialização Efetuada por Terceiros – Itens Produzidos',
'K302':'Produção Conjunta – Industrialização Efetuada por Terceiros – Insumos Consumidos',
'K990':'Encerramento do Bloco K',
'1001':'Abertura do Bloco 1',
'1010':'Obrigatoriedade de registros do Bloco 1',
'1100':'Registro de Informações sobre Exportação',
'1105':'Documentos Fiscais de Exportação',
'1110':'Operações de Exportação Indireta - Mercadorias de terceiros',
'1200':'Controle de Créditos Fiscais - ICMS',
'1210':'Utilização de Créditos Fiscais - ICMS',
'1250':'Informações consolidadas de saldos de restituição, ressarcimento e complemen- tação do ICMS',
'1255':'Informações consolidadas de saldos de restituição, ressarcimento e complemen- tação do ICMS por motivo',
'1300':'Movimentação diária de combustíveis',
'1310':'Movimentação diária de combustíveis por tanque',
'1320':'Volume de vendas',
'1350':'Bombas',
'1360':'Lacres das bombas',
'1370':'Bicos da bomba',
'1390':'Controle de produção de Usina',
'1391':'Produção diária da usina',
'1400':'Informação sobre Valor Agregado',
'1500':'Nota fiscal/Conta de energia elétrica (código 06) - Operações Interestaduais',
'1510':'Itens do documento Nota fiscal/Conta de energia elétrica (código 06)',
'1600':'Total das operações com cartão de crédito e/ou débito',
'1601':'Operações com instrumentos de pagamentos eletrônicos',
'1700':'Documentos fiscais utilizados',
'1710':'Documentos fiscais cancelados/inutilizados',
'1800':'DCTA - Demonstrativo de crédito do ICMS sobre transporte aéreo',
'1900':'Indicador de sub-apuração do ICMS',
'1910':'Período da sub-apuração do ICMS',
'1920':'Sub-apuração do ICMS',
'1921':'Ajuste/benefício/incentivo da sub-apuração do ICMS',
'1922':'Informações adicionais dos ajustes da sub-apuração do ICMS',
'1923':'Informações adicionais dos ajustes da sub-apuração do ICMS - Identificação dos documentos fiscais',
'1925':'Informações adicionais da sub-apuração do ICMS - Valores declaratórios',
'1926':'Obrigações do ICMS a recolher - Operações referentes à sub-apuração do ICMS',
'1960':'GIAF 1 - Guia de informação e apuração de incentivos fiscais e financeiros: indústria (crédito presumido)',
'1970':'GIAF 3 - Guia de informação e apuração de incentivos fiscais e financeiros: importação (diferimento na entrada e crédito presumido na saída subsequente)',
'1975':'GIAF 3 - Guia de informação e apuração de incentivos fiscais e financeiros: importação (saídas internas por faixa de alíquota)  importação (saídas internas por faixa de alíquota)',
'1980':'GIAF 4 - Guia de informação e apuração de incentivos fiscais e financeiros: central de distribuição (entradas/saídas)',
'1990':'Encerramento do Bloco 1',
'9001':'Abertura do Bloco 9',
'9900':'Registros do Arquivo',
'9990':'Encerramento do Bloco 9',
'9999':'Encerramento do Arquivo Digital'}
